export const categoryConstants={
    GET_ALL_CATEGORIES_REQUEST: 'GET ALL CATEGORIES REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET ALL CATEGORIES SUCCESS',
    GET_ALL_CATEGORIES_FAILURE: 'GET ALL CATEGORIES FAILURE',
    ADD_CATEGORIES_REQUEST: 'ADD CATEGORIES REQUEST',
    ADD_CATEGORIES_SUCCESS: 'ADD CATEGORIES SUCCESS',
    ADD_CATEGORIES_FAILURE: 'ADD CATEGORIES FAILURE',
}

