export const categoryConstants={
    GET_ALL_CATEGORIES_REQUEST: 'GET ALL CATEGORIES REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET ALL CATEGORIES SUCCESS',
    GET_ALL_CATEGORIES_FAILURE: 'GET ALL CATEGORIES FAILURE',
    ADD_CATEGORIES_REQUEST: 'ADD CATEGORIES REQUEST',
    ADD_CATEGORIES_SUCCESS: 'ADD CATEGORIES SUCCESS',
    ADD_CATEGORIES_FAILURE: 'ADD CATEGORIES FAILURE',
}

export const productContants = {   
    GET_PRODUCTS_BY_SLUG: 'GET PRODUCTS BY SLUG',
    GET_PRODUCT_PAGE_REQUEST: 'GET PRODUCT PAGE REQUEST',
    GET_PRODUCTS_PAGE_SUCCESS: 'GET PRODUCT PAGE SUCCESS',
    GET_PRODUCTS_PAGE_FAILURE: 'GET PRODUCT PAGE FAILURE',

    GET_PRODUCTS_DETAILS_BY_ID_REQUEST: 'GET PRODUCTS DETAILS BY ID REQUEST',
    GET_PRODUCTS_DETAILS_BY_ID_SUCCESS: 'GET PRODUCTS DETAILS BY ID SUCCESS',
    GET_PRODUCTS_DETAILS_BY_ID_FAILURE: 'GET PRODUCTS DETAILS BY ID FAILURE'
    

}

export const authConstant ={
    LOGIN_REQUEST: 'LOGIN REQUEST',
    LOGIN_SUCCESS: 'LOGIN SUCCESS',
    LOGIN_FAILURE: 'LOGIN FAILURE',
    LOGOUT_REQUEST: 'LOGOUT REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT FAILURE'
}

export const cartConstants = {
    ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
    RESET_CART: "RESET_CART",
  
    REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
    REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
    REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",
  };

  export const userConstants = {
    GET_USER_ADDRESS_REQUEST: "GET_USER_ADDRESS_REQUEST",
    GET_USER_ADDRESS_SUCCESS: "GET_USER_ADDRESS_SUCCESS",
    GET_USER_ADDRESS_FAILURE: "GET_USER_ADDRESS_FAILURE",
    ADD_USER_ADDRESS_REQUEST: "ADD_USER_ADDRESS_REQUEST",
    ADD_USER_ADDRESS_SUCCESS: "ADD_USER_ADDRESS_SUCCESS",
    ADD_USER_ADDRESS_FAILURE: "ADD_USER_ADDRESS_FAILURE",
    ADD_USER_ORDER_REQUEST: "ADD_USER_ORDER_REQUEST",
    ADD_USER_ORDER_SUCCESS: "ADD_USER_ORDER_SUCCESS",
    ADD_USER_ORDER_FAILURE: "ADD_USER_ORDER_FAILURE",
  
    GET_USER_ORDER_REQUEST: "GET_USER_ORDER_REQUEST",
    GET_USER_ORDER_SUCCESS: "GET_USER_ORDER_SUCCESS",
    GET_USER_ORDER_FAILURE: "GET_USER_ORDER_FAILURE",
  
    GET_USER_ORDER_DETAILS_REQUEST: "GET_USER_ORDER_DETAILS_REQUEST",
    GET_USER_ORDER_DETAILS_SUCCESS: "GET_USER_ORDER_DETAILS_SUCCESS",
    GET_USER_ORDER_DETAILS_FAILURE: "GET_USER_ORDER_DETAILS_FAILURE",
  };